"""create questions table

Revision ID: 39f844dd02db
Revises: 
Create Date: 2026-08-21 19:30:38.656109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '39f844dd02db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('MCQ', 'FRQ', name='questiontype'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('unit', sa.Integer(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('choices', sa.JSON(), nullable=True),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('starter_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('public_tests', sa.JSON(), nullable=True),
    sa.Column('hidden_tests', sa.JSON(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_source'), 'questions', ['source'], unique=False)
    op.create_index(op.f('ix_questions_type'), 'questions', ['type'], unique=False)
    op.create_index(op.f('ix_questions_unit'), 'questions', ['unit'], unique=False)
    op.create_index(op.f('ix_questions_year'), 'questions', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_year'), table_name='questions')
    op.drop_index(op.f('ix_questions_unit'), table_name='questions')
    op.drop_index(op.f('ix_questions_type'), table_name='questions')
    op.drop_index(op.f('ix_questions_source'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
